version: '2.3'

services:
  elephants-tool:
    build: service
    restart: always
    ports:
      - 22000:22000
    pids_limit: 512
    mem_limit: 128M
    privileged: true
    container_name: 'elephants-tool'
